"""Create all initial tables

Revision ID: a4ba78d92049
Revises: 
Create Date: 2025-08-10 01:38:28.902461

"""
from typing import Sequence, Union
"""Create all initial tables"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

\
# revision identifiers, used by Alembic.
revision = 'a4ba78d92049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_index(op.f('ix_platform_users_id'), 'platform_users', ['id'], unique=False)
    op.create_table('client_app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('wallet_type', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('billing_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_index(op.f('ix_client_app_users_email'), 'client_app_users', ['email'], unique=True)
    op.create_index(op.f('ix_client_app_users_id'), 'client_app_users', ['id'], unique=False)
    op.create_index(op.f('ix_client_app_users_wallet_address'), 'client_app_users', ['wallet_address'], unique=True)
    op.create_table('client_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('platform_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index(op.f('ix_client_companies_id'), 'client_companies', ['id'], unique=False)
    op.create_index(op.f('ix_client_companies_name'), 'client_companies', ['name'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('anonymous_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('web3_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web3_events_chain_id'), 'web3_events', ['chain_id'], unique=False)
    op.create_index(op.f('ix_web3_events_contract_address'), 'web3_events', ['contract_address'], unique=False)
    op.create_index(op.f('ix_web3_events_id'), 'web3_events', ['id'], unique=False)
    op.create_index(op.f('ix_web3_events_transaction_hash'), 'web3_events', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_web3_events_wallet_address'), 'web3_events', ['wallet_address'], unique=False)
    op.create_table('platform_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('active_sessions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('revenue_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_value_locked', sa.DECIMAL(precision=38, scale=18), nullable=True),
    sa.Column('active_wallets', sa.Integer(), nullable=True),
    sa.Column('transaction_volume_24h', sa.DECIMAL(precision=38, scale=18), nullable=True),
    sa.Column('new_contracts', sa.Integer(), nullable=True),
    sa.Column('daily_page_views', sa.Integer(), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('chain_id', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_metrics_id'), 'platform_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_metrics_id'), table_name='platform_metrics')
    op.drop_table('platform_metrics')
    op.drop_index(op.f('ix_web3_events_wallet_address'), table_name='web3_events')
    op.drop_index(op.f('ix_web3_events_transaction_hash'), table_name='web3_events')
    op.drop_index(op.f('ix_web3_events_id'), table_name='web3_events')
    op.drop_index(op.f('ix_web3_events_contract_address'), table_name='web3_events')
    op.drop_index(op.f('ix_web3_events_chain_id'), table_name='web3_events')
    op.drop_table('web3_events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_client_companies_name'), table_name='client_companies')
    op.drop_index(op.f('ix_client_companies_id'), table_name='client_companies')
    op.drop_table('client_companies')
    op.drop_index(op.f('ix_client_app_users_wallet_address'), table_name='client_app_users')
    op.drop_index(op.f('ix_client_app_users_id'), table_name='client_app_users')
    op.drop_index(op.f('ix_client_app_users_email'), table_name='client_app_users')
    op.drop_table('client_app_users')
    op.drop_index(op.f('ix_platform_users_id'), table_name='platform_users')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.drop_table('platform_users')
    # ### end Alembic commands ###