
"""Add aggregation tables for unified analytics system

Revision ID: b5c6d7e8f901
Revises: a4ba78d92049
Create Date: 2025-09-05 22:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID

# revision identifiers, used by Alembic.
revision = 'b5c6d7e8f901'
down_revision = 'a4ba78d92049'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create raw_events table
    op.create_table('raw_events',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', UUID(as_uuid=True), nullable=False),
        sa.Column('event_name', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('anonymous_id', sa.String(), nullable=True),
        sa.Column('session_id', sa.String(), nullable=True),
        sa.Column('properties', JSONB(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('region', sa.String(), nullable=True),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('wallet_address', sa.String(), nullable=True),
        sa.Column('chain_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_id'), 'raw_events', ['id'], unique=False)
    op.create_index(op.f('ix_raw_events_company_id'), 'raw_events', ['company_id'], unique=False)
    
    # Create campaign_analytics_daily table
    op.create_table('campaign_analytics_daily',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', UUID(as_uuid=True), nullable=False),
        sa.Column('analytics_date', sa.Date(), nullable=False),
        sa.Column('data', JSONB(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_analytics_daily_id'), 'campaign_analytics_daily', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_analytics_daily_company_id'), 'campaign_analytics_daily', ['company_id'], unique=False)
    
    # Create campaign_analytics_hourly table
    op.create_table('campaign_analytics_hourly',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', UUID(as_uuid=True), nullable=False),
        sa.Column('analytics_date', sa.Date(), nullable=False),
        sa.Column('analytics_hour', sa.Integer(), nullable=False),
        sa.Column('data', JSONB(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_analytics_hourly_id'), 'campaign_analytics_hourly', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_analytics_hourly_company_id'), 'campaign_analytics_hourly', ['company_id'], unique=False)
    
    # Create subscription_plans table
    op.create_table('subscription_plans',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', UUID(as_uuid=True), nullable=False),
        sa.Column('plan_tier', sa.Integer(), nullable=False),
        sa.Column('plan_name', sa.String(), nullable=False),
        sa.Column('data_retention_days', sa.Integer(), nullable=False),
        sa.Column('max_events_per_day', sa.Integer(), nullable=True),
        sa.Column('features', JSONB(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_company_id'), 'subscription_plans', ['company_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_company_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_campaign_analytics_hourly_company_id'), table_name='campaign_analytics_hourly')
    op.drop_index(op.f('ix_campaign_analytics_hourly_id'), table_name='campaign_analytics_hourly')
    op.drop_table('campaign_analytics_hourly')
    op.drop_index(op.f('ix_campaign_analytics_daily_company_id'), table_name='campaign_analytics_daily')
    op.drop_index(op.f('ix_campaign_analytics_daily_id'), table_name='campaign_analytics_daily')
    op.drop_table('campaign_analytics_daily')
    op.drop_index(op.f('ix_raw_events_company_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_id'), table_name='raw_events')
    op.drop_table('raw_events')
    # ### end Alembic commands ###
