"""add_wallet_tables

Revision ID: d4e5f6g7h8i9
Revises: c3d4e5f6g7h8
Create Date: 2025-09-19 06:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4e5f6g7h8i9'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create wallet_connections table
    op.create_table('wallet_connections',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('wallet_type', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('wallet_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_connections_id'), 'wallet_connections', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_connections_wallet_address'), 'wallet_connections', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_wallet_connections_company_id'), 'wallet_connections', ['company_id'], unique=False)
    op.create_index('idx_company_wallet', 'wallet_connections', ['company_id', 'wallet_address'], unique=False)
    op.create_unique_constraint('unique_company_wallet', 'wallet_connections', ['company_id', 'wallet_address'])
    
    # Create wallet_activities table
    op.create_table('wallet_activities',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('wallet_connection_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('chain_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('token_symbol', sa.String(), nullable=True),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('gas_price', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_connection_id'], ['wallet_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_activities_id'), 'wallet_activities', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_activities_wallet_connection_id'), 'wallet_activities', ['wallet_connection_id'], unique=False)
    op.create_index(op.f('ix_wallet_activities_transaction_hash'), 'wallet_activities', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_wallet_activities_timestamp'), 'wallet_activities', ['timestamp'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_activities_timestamp'), table_name='wallet_activities')
    op.drop_index(op.f('ix_wallet_activities_transaction_hash'), table_name='wallet_activities')
    op.drop_index(op.f('ix_wallet_activities_wallet_connection_id'), table_name='wallet_activities')
    op.drop_index(op.f('ix_wallet_activities_id'), table_name='wallet_activities')
    op.drop_table('wallet_activities')
    
    op.drop_constraint('unique_company_wallet', 'wallet_connections', type_='unique')
    op.drop_index('idx_company_wallet', table_name='wallet_connections')
    op.drop_index(op.f('ix_wallet_connections_company_id'), table_name='wallet_connections')
    op.drop_index(op.f('ix_wallet_connections_wallet_address'), table_name='wallet_connections')
    op.drop_index(op.f('ix_wallet_connections_id'), table_name='wallet_connections')
    op.drop_table('wallet_connections')
    # ### end Alembic commands ###
